import type { CampaignRouteDefinition, ObbRouteShape, RouteElevationProfile, RouteShape, Vec2Tuple } from './RouteTypes';
import { assertValidRouteDefinition } from './validateRoute';

const BRANCH_STAIR_LANDING_DEPTH = 1.35;

function branchStairElevation(start: number, end: number): RouteElevationProfile {
  return { start, end, landingDepth: BRANCH_STAIR_LANDING_DEPTH };
}

function branchStairHalfExtents(width: number, visibleHalfDepth: number): Vec2Tuple {
  return [width, visibleHalfDepth + BRANCH_STAIR_LANDING_DEPTH];
}

type StairEndpoints = readonly [start: Vec2Tuple, end: Vec2Tuple];

function branchStairForward([start, end]: StairEndpoints): Vec2Tuple {
  const dx = end[0] - start[0];
  const dz = end[1] - start[1];
  const length = Math.hypot(dx, dz) || 1;
  return [dx / length, dz / length];
}

function branchStairObb(width: number, endpoints: StairEndpoints): ObbRouteShape {
  const [start, end] = endpoints;
  const forward = branchStairForward(endpoints);
  return {
    kind: 'obb',
    center: [(start[0] + end[0]) * 0.5, (start[1] + end[1]) * 0.5],
    halfExtents: branchStairHalfExtents(width, Math.hypot(end[0] - start[0], end[1] - start[1]) * 0.5),
    rotation: Math.atan2(-forward[0], forward[1]),
  };
}

const DROWNED_BELFRY_ASCENT: StairEndpoints = [[-5.5, 20.3], [-12.4, 18.1]];
const DROWNED_BELFRY_RETURN: StairEndpoints = [[-13.5, 14.3], [-8.2, 8.7]];
const GRAVEGLASS_DESCENT: StairEndpoints = [[5.1, 19.25], [9.65, 16.8]];
const GRAVEGLASS_RETURN: StairEndpoints = [[9.35, 13.9], [-6.5, 9.2]];

/**
 * The first authored pilgrimage through the Last Firmament. Coordinates are
 * renderer-independent X/Z tuples so simulation, validation, and tooling can
 * consume this definition without constructing Three.js objects.
 */
export const FIRMAMENT_ROUTE = assertValidRouteDefinition({
  version: 1,
  id: 'last-firmament-pilgrimage',
  name: 'The Pilgrimage to Moonfall Observatory',
  start: {
    sectionId: 'spiral-threshold',
    position: [0, 46],
    facingRadians: Math.PI,
  },
  requirements: {
    encounterCount: 5,
    minimumBridgeSections: 3,
    minimumBiomeCount: 5,
    minimumChoiceCount: 4,
    relicOrder: ['moon', 'aurora', 'constellation'],
    enemyKinds: [
      'wisp',
      'sentinel',
      'seer',
      'ashenInitiate',
      'astralLancer',
      'eclipseChorister',
      'emberPenitent',
      'drownedCantor',
      'prismScribe',
      'thornReliquary',
      'orreryCastellan',
      'eclipseArchon',
    ],
  },
  sections: [
    {
      id: 'spiral-threshold',
      name: 'Spiral Threshold',
      order: 0,
      kind: 'safe',
      safe: true,
      connectsTo: ['ashen-processional'],
      walkable: [{ kind: 'circle', center: [0, 46], radius: 7 }],
      cameraForward: [0, -1],
      enemyAnchors: [],
    },
    {
      id: 'ashen-processional',
      name: 'Ashen Processional',
      order: 1,
      kind: 'processional',
      safe: false,
      connectsTo: ['spiral-threshold', 'moon-court'],
      walkable: [{ kind: 'obb', center: [0, 34], halfExtents: [4.6, 8.2], rotation: 0 }],
      cameraForward: [0, -1],
      enemyAnchors: [
        { id: 'processional-left-vantage', position: [-2.5, 35] },
        { id: 'processional-center-guard', position: [0, 31] },
        { id: 'processional-right-vantage', position: [2.3, 28.5] },
      ],
    },
    {
      id: 'moon-court',
      name: 'Court of the Pale Moon',
      order: 2,
      kind: 'court',
      safe: true,
      connectsTo: ['ashen-processional', 'fallen-orbit-bridge', 'drowned-belfry-ascent', 'graveglass-descent'],
      walkable: [{ kind: 'circle', center: [0, 22], radius: 6.5 }],
      cameraForward: [-0.5, -0.866],
      enemyAnchors: [],
    },
    {
      id: 'fallen-orbit-bridge',
      name: 'Bridge of Fallen Orbits',
      order: 3,
      kind: 'bridge',
      safe: false,
      connectsTo: ['moon-court', 'orrery-court', 'drowned-belfry-return', 'graveglass-return'],
      walkable: [{ kind: 'obb', center: [-5.5, 11.5], halfExtents: [2.4, 11.5], rotation: -Math.PI / 6 }],
      cameraForward: [-0.5, -0.866],
      enemyAnchors: [
        { id: 'fallen-orbit-entry', position: [-1, 19] },
        { id: 'fallen-orbit-midspan', position: [-6, 10] },
        { id: 'fallen-orbit-far-vantage', position: [-10, 3.5] },
      ],
    },
    {
      id: 'orrery-court',
      name: 'Court of the Broken Orrery',
      order: 4,
      kind: 'boss-arena',
      safe: false,
      connectsTo: ['fallen-orbit-bridge', 'aurora-span'],
      walkable: [{ kind: 'circle', center: [-11.5, -3.5], radius: 7.2 }],
      cameraForward: [0.707, -0.707],
      enemyAnchors: [{ id: 'orrery-heart', position: [-11.5, -4] }],
    },
    {
      id: 'aurora-span',
      name: 'Aurora Span',
      order: 5,
      kind: 'bridge',
      safe: true,
      connectsTo: ['orrery-court', 'aurora-refuge'],
      walkable: [{ kind: 'obb', center: [-2.5, -14.5], halfExtents: [2.5, 13.5], rotation: Math.PI / 4 }],
      cameraForward: [0.707, -0.707],
      enemyAnchors: [],
    },
    {
      id: 'aurora-refuge',
      name: 'Aurora Refuge',
      order: 6,
      kind: 'refuge',
      safe: true,
      connectsTo: ['aurora-span', 'sundered-causeway', 'verdant-canopy-ascent', 'bloodroot-descent'],
      walkable: [{ kind: 'circle', center: [7, -25], radius: 5.8 }],
      cameraForward: [0, -1],
      enemyAnchors: [],
    },
    {
      id: 'sundered-causeway',
      name: 'Sundered Causeway',
      order: 7,
      kind: 'causeway',
      safe: false,
      connectsTo: ['aurora-refuge', 'conjunction-cloister', 'verdant-canopy-return', 'bloodroot-return'],
      walkable: [{ kind: 'obb', center: [7, -35], halfExtents: [2.3, 7.5], rotation: 0 }],
      cameraForward: [0, -1],
      enemyAnchors: [
        { id: 'sundered-entry', position: [7, -31] },
        { id: 'sundered-charge-lane', position: [7, -37] },
      ],
    },
    {
      id: 'conjunction-cloister',
      name: 'Conjunction Cloister',
      order: 8,
      kind: 'court',
      safe: false,
      connectsTo: ['sundered-causeway', 'eclipse-causeway', 'ember-choir-ascent', 'ember-furnace-descent'],
      walkable: [{ kind: 'circle', center: [7, -46], radius: 7 }],
      cameraForward: [-0.259, -0.966],
      enemyAnchors: [
        { id: 'cloister-seer-focus', position: [3.1, -42.8] },
        { id: 'cloister-choir-dais', position: [10, -44] },
      ],
    },
    {
      id: 'eclipse-causeway',
      name: 'Eclipse Causeway',
      order: 9,
      kind: 'causeway',
      safe: true,
      connectsTo: [
        'conjunction-cloister',
        'moonfall-observatory',
        'ember-loft-return',
        'ember-furnace-return',
        'amethyst-null-descent',
        'amethyst-archive-ascent',
      ],
      walkable: [{ kind: 'obb', center: [3.5, -56], halfExtents: [2.7, 8.4], rotation: -Math.PI / 12 }],
      cameraForward: [-0.259, -0.966],
      enemyAnchors: [],
    },
    {
      id: 'moonfall-observatory',
      name: 'Moonfall Observatory',
      order: 10,
      kind: 'boss-arena',
      safe: false,
      connectsTo: ['eclipse-causeway', 'amethyst-null-return', 'amethyst-archive-return'],
      walkable: [{ kind: 'circle', center: [0, -67], radius: 10 }],
      cameraForward: [0, -1],
      enemyAnchors: [{ id: 'observatory-eclipse-seal', position: [0, -68] }],
    },
  ],
  branchSections: [
    {
      id: 'drowned-belfry-ascent',
      choiceId: 'drowned-vow',
      optionId: 'still-the-bells',
      name: 'Moon-Belfry Ascent',
      kind: 'stair',
      biome: 'drowned-cloister',
      elevation: branchStairElevation(0, 3.2),
      safe: false,
      connectsTo: ['moon-court', 'drowned-pale-belfry'],
      walkable: [branchStairObb(2.1, DROWNED_BELFRY_ASCENT)],
      cameraForward: branchStairForward(DROWNED_BELFRY_ASCENT),
      enemyAnchors: [],
    },
    {
      id: 'drowned-pale-belfry',
      choiceId: 'drowned-vow',
      optionId: 'still-the-bells',
      name: 'Pale Belfry of the Drowned Saint',
      kind: 'cathedral',
      biome: 'drowned-cloister',
      elevation: { start: 3.2, end: 3.2 },
      safe: false,
      connectsTo: ['drowned-belfry-ascent', 'drowned-belfry-return'],
      walkable: [{ kind: 'circle', center: [-16, 17], radius: 4.4 }],
      cameraForward: branchStairForward(DROWNED_BELFRY_RETURN),
      enemyAnchors: [
        { id: 'drowned-bell-heart', position: [-16, 16.5] },
        { id: 'drowned-bell-left', position: [-18, 18] },
        { id: 'drowned-bell-right', position: [-14, 18] },
      ],
    },
    {
      id: 'drowned-belfry-return',
      choiceId: 'drowned-vow',
      optionId: 'still-the-bells',
      name: 'Belfry Return Stair',
      kind: 'stair',
      biome: 'drowned-cloister',
      elevation: branchStairElevation(3.2, 0),
      safe: false,
      connectsTo: ['drowned-pale-belfry', 'fallen-orbit-bridge'],
      walkable: [branchStairObb(2.1, DROWNED_BELFRY_RETURN)],
      cameraForward: branchStairForward(DROWNED_BELFRY_RETURN),
      enemyAnchors: [],
    },
    {
      id: 'graveglass-descent',
      choiceId: 'drowned-vow',
      optionId: 'take-the-graveglass',
      name: 'Graveglass Descent',
      kind: 'stair',
      biome: 'drowned-cloister',
      elevation: branchStairElevation(0, -2.4),
      safe: false,
      connectsTo: ['moon-court', 'graveglass-crypt'],
      walkable: [branchStairObb(2.1, GRAVEGLASS_DESCENT)],
      cameraForward: branchStairForward(GRAVEGLASS_DESCENT),
      enemyAnchors: [],
    },
    {
      id: 'graveglass-crypt',
      choiceId: 'drowned-vow',
      optionId: 'take-the-graveglass',
      name: 'Graveglass Crypt',
      kind: 'crypt',
      biome: 'drowned-cloister',
      elevation: { start: -2.4, end: -2.4 },
      safe: false,
      connectsTo: ['graveglass-descent', 'graveglass-return'],
      walkable: [{ kind: 'circle', center: [13, 15], radius: 4.5 }],
      cameraForward: branchStairForward(GRAVEGLASS_RETURN),
      enemyAnchors: [
        { id: 'graveglass-center', position: [13, 15] },
        { id: 'graveglass-left', position: [11.5, 15] },
        { id: 'graveglass-right', position: [14.5, 15] },
      ],
    },
    {
      id: 'graveglass-return',
      choiceId: 'drowned-vow',
      optionId: 'take-the-graveglass',
      name: 'Graveglass Return',
      kind: 'stair',
      biome: 'drowned-cloister',
      elevation: branchStairElevation(-2.4, 0),
      safe: false,
      connectsTo: ['graveglass-crypt', 'fallen-orbit-bridge'],
      walkable: [branchStairObb(2.1, GRAVEGLASS_RETURN)],
      cameraForward: branchStairForward(GRAVEGLASS_RETURN),
      enemyAnchors: [],
    },
    {
      id: 'verdant-canopy-ascent',
      choiceId: 'verdant-covenant',
      optionId: 'tend-the-seed',
      name: 'Canopy Glass Ascent',
      kind: 'stair',
      biome: 'verdant-cathedral',
      elevation: branchStairElevation(0, 2.2),
      safe: false,
      connectsTo: ['aurora-refuge', 'verdant-glasshouse'],
      walkable: [{ kind: 'obb', center: [3.6971, -29.8029], halfExtents: branchStairHalfExtents(2.1, 4.05), rotation: 2.1815 }],
      cameraForward: [-0.707, -0.707],
      enemyAnchors: [],
    },
    {
      id: 'verdant-glasshouse',
      choiceId: 'verdant-covenant',
      optionId: 'tend-the-seed',
      name: 'Cathedral Glasshouse',
      kind: 'garden',
      biome: 'verdant-cathedral',
      elevation: { start: 2.2, end: 2.2 },
      safe: false,
      connectsTo: ['verdant-canopy-ascent', 'verdant-canopy-return'],
      walkable: [{ kind: 'circle', center: [-3, -35], radius: 4.8 }],
      cameraForward: [0.819, -0.573],
      enemyAnchors: [
        { id: 'glasshouse-heart', position: [-3, -35] },
        { id: 'glasshouse-west', position: [-5, -34] },
        { id: 'glasshouse-east', position: [-1, -36] },
      ],
    },
    {
      id: 'verdant-canopy-return',
      choiceId: 'verdant-covenant',
      optionId: 'tend-the-seed',
      name: 'Canopy Return Stair',
      kind: 'stair',
      biome: 'verdant-cathedral',
      elevation: branchStairElevation(2.2, 0),
      safe: false,
      connectsTo: ['verdant-glasshouse', 'sundered-causeway'],
      walkable: [{ kind: 'obb', center: [3.9665, -39.8758], halfExtents: branchStairHalfExtents(2.1, 4.05), rotation: -2.1815 }],
      cameraForward: [0.819, -0.573],
      enemyAnchors: [],
    },
    {
      id: 'bloodroot-descent',
      choiceId: 'verdant-covenant',
      optionId: 'harvest-the-root',
      name: 'Bloodroot Descent',
      kind: 'stair',
      biome: 'verdant-cathedral',
      elevation: branchStairElevation(0, -1.8),
      safe: false,
      connectsTo: ['aurora-refuge', 'bloodroot-basin'],
      walkable: [{ kind: 'obb', center: [10.3029, -29.8029], halfExtents: branchStairHalfExtents(2.1, 4.05), rotation: -2.1815 }],
      cameraForward: [0.707, -0.707],
      enemyAnchors: [],
    },
    {
      id: 'bloodroot-basin',
      choiceId: 'verdant-covenant',
      optionId: 'harvest-the-root',
      name: 'Bloodroot Baptistry',
      kind: 'open-area',
      biome: 'verdant-cathedral',
      elevation: { start: -1.8, end: -1.8 },
      safe: false,
      connectsTo: ['bloodroot-descent', 'bloodroot-return'],
      walkable: [{ kind: 'circle', center: [17, -35], radius: 4.8 }],
      cameraForward: [-0.819, -0.573],
      enemyAnchors: [
        { id: 'bloodroot-heart', position: [17, -35] },
        { id: 'bloodroot-west', position: [14.5, -34] },
        { id: 'bloodroot-east', position: [19, -37] },
      ],
    },
    {
      id: 'bloodroot-return',
      choiceId: 'verdant-covenant',
      optionId: 'harvest-the-root',
      name: 'Bloodroot Return',
      kind: 'stair',
      biome: 'verdant-cathedral',
      elevation: branchStairElevation(-1.8, 0),
      safe: false,
      connectsTo: ['bloodroot-basin', 'sundered-causeway'],
      walkable: [{ kind: 'obb', center: [10.0335, -39.8758], halfExtents: branchStairHalfExtents(2.1, 4.05), rotation: 2.1815 }],
      cameraForward: [-0.819, -0.573],
      enemyAnchors: [],
    },
    {
      id: 'ember-choir-ascent',
      choiceId: 'ember-rite',
      optionId: 'still-the-solar-bells',
      name: 'Solar Choir Ascent',
      kind: 'stair',
      biome: 'ember-basilica',
      elevation: branchStairElevation(0, 4),
      safe: false,
      connectsTo: ['conjunction-cloister', 'ember-cathedral-nave'],
      walkable: [{ kind: 'obb', center: [2.4268, -47.8995], halfExtents: branchStairHalfExtents(1.65, 4.92), rotation: 1.7127 }],
      cameraForward: [-0.97, -0.24],
      enemyAnchors: [],
    },
    {
      id: 'ember-cathedral-nave',
      choiceId: 'ember-rite',
      optionId: 'still-the-solar-bells',
      name: 'Vermilion Bell Nave',
      kind: 'cathedral',
      biome: 'ember-basilica',
      elevation: { start: 4, end: 4 },
      safe: false,
      connectsTo: ['ember-choir-ascent', 'ember-loft-return'],
      walkable: [{ kind: 'circle', center: [-7, -49.5], radius: 5 }],
      cameraForward: [0.98, -0.23],
      enemyAnchors: [
        { id: 'ember-nave-heart', position: [-7, -50.5] },
        { id: 'ember-nave-left', position: [-9.4, -48.3] },
        { id: 'ember-nave-right', position: [-4.6, -48.3] },
      ],
    },
    {
      id: 'ember-loft-return',
      choiceId: 'ember-rite',
      optionId: 'still-the-solar-bells',
      name: 'Bell Loft Return',
      kind: 'stair',
      biome: 'ember-basilica',
      elevation: branchStairElevation(4, 0),
      safe: false,
      connectsTo: ['ember-cathedral-nave', 'eclipse-causeway'],
      walkable: [{ kind: 'obb', center: [-0.25, -53.25], halfExtents: branchStairHalfExtents(1.65, 4.1), rotation: -2.064 }],
      cameraForward: [0.88, -0.474],
      enemyAnchors: [],
    },
    {
      id: 'ember-furnace-descent',
      choiceId: 'ember-rite',
      optionId: 'relight-the-sun-heart',
      name: 'Sun-Furnace Descent',
      kind: 'stair',
      biome: 'ember-basilica',
      elevation: branchStairElevation(0, -3),
      safe: false,
      connectsTo: ['conjunction-cloister', 'ember-sunheart-crypt'],
      walkable: [{ kind: 'obb', center: [10.6308, -47.952], halfExtents: branchStairHalfExtents(1.7, 3.98), rotation: -1.7762 }],
      cameraForward: [0.95, -0.32],
      enemyAnchors: [],
    },
    {
      id: 'ember-sunheart-crypt',
      choiceId: 'ember-rite',
      optionId: 'relight-the-sun-heart',
      name: 'Sun-Heart Furnace Crypt',
      kind: 'crypt',
      biome: 'ember-basilica',
      elevation: { start: -3, end: -3 },
      safe: false,
      connectsTo: ['ember-furnace-descent', 'ember-furnace-return'],
      walkable: [{ kind: 'circle', center: [19, -50], radius: 5 }],
      cameraForward: [-0.987, -0.162],
      enemyAnchors: [
        { id: 'ember-furnace-heart', position: [19, -50] },
        { id: 'ember-furnace-left', position: [17, -48] },
        { id: 'ember-furnace-right', position: [21, -52] },
      ],
    },
    {
      id: 'ember-furnace-return',
      choiceId: 'ember-rite',
      optionId: 'relight-the-sun-heart',
      name: 'Furnace Return Stair',
      kind: 'stair',
      biome: 'ember-basilica',
      elevation: branchStairElevation(-3, 0),
      safe: false,
      connectsTo: ['ember-sunheart-crypt', 'eclipse-causeway'],
      walkable: [{ kind: 'obb', center: [9.7639, -54.618], halfExtents: branchStairHalfExtents(1.7, 5.33), rotation: 2.0344 }],
      cameraForward: [-0.8944, -0.4472],
      enemyAnchors: [],
    },
    {
      id: 'amethyst-null-descent',
      choiceId: 'amethyst-confession',
      optionId: 'seal-the-null',
      name: 'Null Choir Descent',
      kind: 'stair',
      biome: 'amethyst-archives',
      elevation: branchStairElevation(0, -4.2),
      safe: false,
      connectsTo: ['eclipse-causeway', 'amethyst-null-choir'],
      walkable: [{ kind: 'obb', center: [-1.518, -57.7255], halfExtents: branchStairHalfExtents(1.65, 6.13), rotation: 1.8737 }],
      cameraForward: [-0.955, -0.298],
      enemyAnchors: [],
    },
    {
      id: 'amethyst-null-choir',
      choiceId: 'amethyst-confession',
      optionId: 'seal-the-null',
      name: 'Starless Null Choir',
      kind: 'cathedral',
      biome: 'amethyst-archives',
      elevation: { start: -4.2, end: -4.2 },
      safe: false,
      connectsTo: ['amethyst-null-descent', 'amethyst-null-return'],
      walkable: [{ kind: 'circle', center: [-12, -61], radius: 5.2 }],
      cameraForward: [0.974, -0.225],
      enemyAnchors: [
        { id: 'null-choir-heart', position: [-12, -61] },
        { id: 'null-choir-left', position: [-14, -60] },
        { id: 'null-choir-right', position: [-10, -63] },
      ],
    },
    {
      id: 'amethyst-null-return',
      choiceId: 'amethyst-confession',
      optionId: 'seal-the-null',
      name: 'Null Choir Return',
      kind: 'stair',
      biome: 'amethyst-archives',
      elevation: branchStairElevation(-4.2, 0),
      safe: false,
      connectsTo: ['amethyst-null-choir', 'moonfall-observatory'],
      walkable: [{ kind: 'obb', center: [-2.9667, -63.0852], halfExtents: branchStairHalfExtents(1.65, 4.42), rotation: -1.7976 }],
      cameraForward: [0.974, -0.225],
      enemyAnchors: [],
    },
    {
      id: 'amethyst-archive-ascent',
      choiceId: 'amethyst-confession',
      optionId: 'drink-the-conjunction',
      name: 'Levitating Archive Ascent',
      kind: 'stair',
      biome: 'amethyst-archives',
      elevation: branchStairElevation(0, 5),
      safe: false,
      connectsTo: ['eclipse-causeway', 'levitating-amethyst-archive'],
      walkable: [{ kind: 'obb', center: [7.6004, -57.4991], halfExtents: branchStairHalfExtents(1.65, 4.25), rotation: -1.9656 }],
      cameraForward: [0.923, -0.385],
      enemyAnchors: [],
    },
    {
      id: 'levitating-amethyst-archive',
      choiceId: 'amethyst-confession',
      optionId: 'drink-the-conjunction',
      name: 'Levitating Amethyst Archive',
      kind: 'archive',
      biome: 'amethyst-archives',
      elevation: { start: 5, end: 5 },
      safe: false,
      connectsTo: ['amethyst-archive-ascent', 'amethyst-archive-return'],
      walkable: [{ kind: 'circle', center: [16, -61], radius: 5.2 }],
      cameraForward: [-0.981, -0.196],
      enemyAnchors: [
        { id: 'archive-heart', position: [16, -61] },
        { id: 'archive-left', position: [14, -59] },
        { id: 'archive-right', position: [18, -63] },
      ],
    },
    {
      id: 'amethyst-archive-return',
      choiceId: 'amethyst-confession',
      optionId: 'drink-the-conjunction',
      name: 'Archive Return Stair',
      kind: 'stair',
      biome: 'amethyst-archives',
      elevation: branchStairElevation(5, 0),
      safe: false,
      connectsTo: ['levitating-amethyst-archive', 'moonfall-observatory'],
      walkable: [{ kind: 'obb', center: [5.9504, -63.0094], halfExtents: branchStairHalfExtents(1.65, 5.4), rotation: 1.7682 }],
      cameraForward: [-0.981, -0.196],
      enemyAnchors: [],
    },
  ],
  gates: [
    {
      id: 'threshold-portcullis',
      name: 'Threshold Portcullis',
      sectionId: 'ashen-processional',
      collider: { a: [-5, 40.5], b: [5, 40.5], thickness: 0.42 },
      initialState: 'open',
    },
    {
      id: 'moon-seal',
      name: 'Pale Moon Seal',
      sectionId: 'moon-court',
      collider: { a: [-5.2, 26.4], b: [5.2, 26.4], thickness: 0.48 },
      initialState: 'closed',
    },
    {
      id: 'orrery-seal',
      name: 'Broken Orrery Seal',
      sectionId: 'fallen-orbit-bridge',
      collider: { a: [-13.7427, 4.4226], b: [-7.5073, 0.8226], thickness: 0.5 },
      initialState: 'closed',
    },
    {
      id: 'aurora-seal',
      name: 'Verdant Aurora Seal',
      sectionId: 'aurora-span',
      collider: { a: [-8.9042, -12.9042], b: [-4.0958, -8.0958], thickness: 0.5 },
      initialState: 'closed',
    },
    {
      id: 'eclipse-seal',
      name: 'Conjunction Eclipse Seal',
      sectionId: 'eclipse-causeway',
      collider: { a: [1.0227, -52.5683], b: [7.9773, -54.4317], thickness: 0.56 },
      initialState: 'closed',
    },
    {
      id: 'drowned-direct-seal',
      name: 'Drowned Cloister Direct Seal',
      sectionId: 'fallen-orbit-bridge',
      collider: { a: [-6.1, 16.5], b: [-0.9, 13.5], thickness: 0.52 },
      initialState: 'closed',
    },
    {
      id: 'drowned-belfry-entry',
      name: 'Pale Belfry Vow',
      sectionId: 'drowned-belfry-ascent',
      collider: { a: [-6.7, 22.3], b: [-5.3, 17.9], thickness: 0.48 },
      initialState: 'open',
    },
    {
      id: 'graveglass-entry',
      name: 'Graveglass Vow',
      sectionId: 'graveglass-descent',
      collider: { a: [4.45, 17], b: [6.65, 21], thickness: 0.48 },
      initialState: 'open',
    },
    {
      id: 'drowned-belfry-exit',
      name: 'Pale Belfry Absolution',
      sectionId: 'drowned-belfry-return',
      collider: { a: [-14.8, 12.4], b: [-11.45, 15.55], thickness: 0.48 },
      initialState: 'closed',
    },
    {
      id: 'graveglass-exit',
      name: 'Graveglass Absolution',
      sectionId: 'graveglass-return',
      collider: { a: [8.2, 16], b: [9.55, 11.55], thickness: 0.48 },
      initialState: 'closed',
    },
    {
      id: 'verdant-direct-seal',
      name: 'Verdant Cathedral Direct Seal',
      sectionId: 'sundered-causeway',
      collider: { a: [4.2, -35], b: [9.8, -35], thickness: 0.52 },
      initialState: 'closed',
    },
    {
      id: 'verdant-canopy-entry',
      name: 'Glasshouse Covenant',
      sectionId: 'verdant-canopy-ascent',
      collider: { a: [4.958, -31.603], b: [2.436, -27.997], thickness: 0.48 },
      initialState: 'open',
    },
    {
      id: 'bloodroot-entry',
      name: 'Bloodroot Covenant',
      sectionId: 'bloodroot-descent',
      collider: { a: [11.564, -28.0], b: [9.042, -31.606], thickness: 0.48 },
      initialState: 'open',
    },
    {
      id: 'verdant-canopy-exit',
      name: 'Glasshouse Benediction',
      sectionId: 'verdant-canopy-return',
      collider: { a: [0.797, -40.22], b: [3.203, -36.78], thickness: 0.48 },
      initialState: 'closed',
    },
    {
      id: 'bloodroot-exit',
      name: 'Bloodroot Benediction',
      sectionId: 'bloodroot-return',
      collider: { a: [10.797, -36.78], b: [13.203, -40.22], thickness: 0.48 },
      initialState: 'closed',
    },
    {
      id: 'ember-direct-seal',
      name: 'Vermilion Basilica Direct Seal',
      sectionId: 'eclipse-causeway',
      collider: { a: [2.81, -49.17], b: [8.99, -50.83], thickness: 0.52 },
      initialState: 'closed',
    },
    {
      id: 'ember-choir-entry',
      name: 'Solar Bell Rite',
      sectionId: 'ember-choir-ascent',
      collider: { a: [1.175, -45.8], b: [0.475, -50.4], thickness: 0.48 },
      initialState: 'open',
    },
    {
      id: 'ember-furnace-entry',
      name: 'Sun-Heart Rite',
      sectionId: 'ember-furnace-descent',
      collider: { a: [11.255, -46.1], b: [10.007, -49.804], thickness: 0.48 },
      initialState: 'open',
    },
    {
      id: 'ember-choir-exit',
      name: 'Solar Choir Absolution',
      sectionId: 'ember-loft-return',
      collider: { a: [-2.018, -50.448], b: [-3.582, -53.352], thickness: 0.48 },
      initialState: 'closed',
    },
    {
      id: 'ember-furnace-exit',
      name: 'Sun-Heart Absolution',
      sectionId: 'ember-furnace-return',
      collider: { a: [14.872, -54.243], b: [13.128, -50.757], thickness: 0.48 },
      initialState: 'closed',
    },
    {
      id: 'amethyst-direct-seal',
      name: 'Amethyst Archive Direct Seal',
      sectionId: 'moonfall-observatory',
      collider: { a: [-0.29, -58.67], b: [5.89, -60.33], thickness: 0.52 },
      initialState: 'closed',
    },
    {
      id: 'amethyst-null-entry',
      name: 'Null Confession',
      sectionId: 'amethyst-null-descent',
      collider: { a: [-0.6, -54.2], b: [-1.7, -58.8], thickness: 0.48 },
      initialState: 'open',
    },
    {
      id: 'amethyst-archive-entry',
      name: 'Conjunction Confession',
      sectionId: 'amethyst-archive-ascent',
      collider: { a: [9.576, -60.915], b: [11.424, -56.485], thickness: 0.48 },
      initialState: 'open',
    },
    {
      id: 'amethyst-null-exit',
      name: 'Null Choir Absolution',
      sectionId: 'amethyst-null-return',
      collider: { a: [-5.973, -64.545], b: [-5.027, -60.455], thickness: 0.48 },
      initialState: 'closed',
    },
    {
      id: 'amethyst-archive-exit',
      name: 'Levitating Index Absolution',
      sectionId: 'amethyst-archive-return',
      collider: { a: [8.088, -60.441], b: [8.912, -64.559], thickness: 0.48 },
      initialState: 'closed',
    },
  ],
  checkpoints: [
    {
      id: 'moon-relic',
      name: 'Body of the Pale Moon',
      order: 0,
      sectionId: 'moon-court',
      position: [0, 24.5],
      facingRadians: -Math.PI / 6,
      activationRadius: 1.8,
      relicKind: 'moon',
      unlocksAfterEncounterId: 'ashen-processional-ward',
    },
    {
      id: 'aurora-relic',
      name: 'Body of the Verdant Aurora',
      order: 1,
      sectionId: 'aurora-refuge',
      position: [7, -23.5],
      facingRadians: Math.PI,
      activationRadius: 1.8,
      relicKind: 'aurora',
      unlocksAfterEncounterId: 'orrery-castellan',
    },
    {
      id: 'constellation-relic',
      name: 'Body of the Lost Conjunction',
      order: 2,
      sectionId: 'conjunction-cloister',
      position: [7, -42.5],
      facingRadians: -Math.PI / 12,
      activationRadius: 1.8,
      relicKind: 'constellation',
      unlocksAfterEncounterId: 'choristers-of-the-sundered-span',
    },
  ],
  choices: [
    {
      id: 'drowned-vow',
      name: 'Vow of the Drowned Cloister',
      sectionId: 'moon-court',
      position: [0, 18.6],
      activationRadius: 2.25,
      prompt: 'Choose what the drowned bells will remember.',
      directGateId: 'drowned-direct-seal',
      options: [
        {
          id: 'still-the-bells',
          label: 'Still the drowned bells',
          description: 'Climb the pale belfry. Mercy quiets its choir and favors protective vestments.',
          sectionIds: ['drowned-belfry-ascent', 'drowned-pale-belfry', 'drowned-belfry-return'],
          entryGateId: 'drowned-belfry-entry',
          exitGateId: 'drowned-belfry-exit',
          encounterId: 'drowned-belfry-cantors',
          consequence: {
            affinity: 'mercy',
            affinityDelta: 0.16,
            lootBias: 'robe',
            enemyPowerMultiplier: 0.97,
            rewardLabel: 'The bells fall mercifully silent',
          },
        },
        {
          id: 'take-the-graveglass',
          label: 'Take the graveglass',
          description: 'Descend beneath the waterline. Wrath claims stronger catalysts but wakes harder foes.',
          sectionIds: ['graveglass-descent', 'graveglass-crypt', 'graveglass-return'],
          entryGateId: 'graveglass-entry',
          exitGateId: 'graveglass-exit',
          encounterId: 'graveglass-dead',
          consequence: {
            affinity: 'wrathful',
            affinityDelta: 0.14,
            lootBias: 'catalyst',
            enemyPowerMultiplier: 1.06,
            rewardLabel: 'Graveglass answers the hand that stole it',
          },
        },
      ],
    },
    {
      id: 'verdant-covenant',
      name: 'Covenant of the Rooted Dawn',
      sectionId: 'aurora-refuge',
      position: [7, -29.2],
      activationRadius: 2.35,
      prompt: 'Decide whether the cathedral garden is tended or harvested.',
      directGateId: 'verdant-direct-seal',
      options: [
        {
          id: 'tend-the-seed',
          label: 'Tend the aurora seed',
          description: 'Ascend through the glass canopy. Restoration and vitality grow from restraint.',
          sectionIds: ['verdant-canopy-ascent', 'verdant-glasshouse', 'verdant-canopy-return'],
          entryGateId: 'verdant-canopy-entry',
          exitGateId: 'verdant-canopy-exit',
          encounterId: 'garden-grafts',
          consequence: {
            affinity: 'mercy',
            affinityDelta: 0.18,
            lootBias: 'charm',
            enemyPowerMultiplier: 0.98,
            rewardLabel: 'The seed remembers a gentler dawn',
          },
        },
        {
          id: 'harvest-the-root',
          label: 'Harvest the bloodroot',
          description: 'Descend into the baptistry. Its weapons are potent, but every later foe drinks the same sap.',
          sectionIds: ['bloodroot-descent', 'bloodroot-basin', 'bloodroot-return'],
          entryGateId: 'bloodroot-entry',
          exitGateId: 'bloodroot-exit',
          encounterId: 'bloodroot-reliquary',
          consequence: {
            affinity: 'wrathful',
            affinityDelta: 0.18,
            lootBias: 'weapon',
            enemyPowerMultiplier: 1.08,
            rewardLabel: 'The severed root hardens into a weapon',
          },
        },
      ],
    },
    {
      id: 'ember-rite',
      name: 'Rite of the Vermilion Basilica',
      sectionId: 'conjunction-cloister',
      position: [7, -49],
      activationRadius: 2.4,
      prompt: 'Choose whether the red cathedral is silenced or relit.',
      directGateId: 'ember-direct-seal',
      options: [
        {
          id: 'still-the-solar-bells',
          label: 'Still the solar bells',
          description: 'Take the high choir stair and silence the bell-knights before their final toll.',
          sectionIds: ['ember-choir-ascent', 'ember-cathedral-nave', 'ember-loft-return'],
          entryGateId: 'ember-choir-entry',
          exitGateId: 'ember-choir-exit',
          encounterId: 'ember-choir-penitents',
          consequence: {
            affinity: 'celestial',
            affinityDelta: 0.2,
            lootBias: 'charm',
            enemyPowerMultiplier: 0.96,
            rewardLabel: 'Silence becomes a ward against the final hymn',
          },
        },
        {
          id: 'relight-the-sun-heart',
          label: 'Relight the sun-heart',
          description: 'Enter the furnace crypt. Ember-forged arms awaken alongside harsher celestial trials.',
          sectionIds: ['ember-furnace-descent', 'ember-sunheart-crypt', 'ember-furnace-return'],
          entryGateId: 'ember-furnace-entry',
          exitGateId: 'ember-furnace-exit',
          encounterId: 'ember-furnace-penitents',
          consequence: {
            affinity: 'wrathful',
            affinityDelta: 0.22,
            lootBias: 'weapon',
            enemyPowerMultiplier: 1.1,
            rewardLabel: 'The sun-heart burns inside mortal steel',
          },
        },
      ],
    },
    {
      id: 'amethyst-confession',
      name: 'Confession of the Amethyst Archives',
      sectionId: 'eclipse-causeway',
      position: [3.5, -56.2],
      activationRadius: 2.45,
      prompt: 'Confess what should become of the unwritten conjunction.',
      directGateId: 'amethyst-direct-seal',
      options: [
        {
          id: 'seal-the-null',
          label: 'Seal the null choir',
          description: 'Descend into the inverted nave and close the memory that should never have sung.',
          sectionIds: ['amethyst-null-descent', 'amethyst-null-choir', 'amethyst-null-return'],
          entryGateId: 'amethyst-null-entry',
          exitGateId: 'amethyst-null-exit',
          encounterId: 'amethyst-null-scribes',
          consequence: {
            affinity: 'mercy',
            affinityDelta: 0.24,
            lootBias: 'robe',
            enemyPowerMultiplier: 0.92,
            rewardLabel: 'The null is sealed; the mended firmament waits',
          },
        },
        {
          id: 'drink-the-conjunction',
          label: 'Drink the conjunction',
          description: 'Climb the levitating archive and consume its forbidden ability. The Archon will answer in kind.',
          sectionIds: ['amethyst-archive-ascent', 'levitating-amethyst-archive', 'amethyst-archive-return'],
          entryGateId: 'amethyst-archive-entry',
          exitGateId: 'amethyst-archive-exit',
          encounterId: 'amethyst-archive-scribes',
          consequence: {
            affinity: 'wrathful',
            affinityDelta: 0.26,
            lootBias: 'catalyst',
            enemyPowerMultiplier: 1.14,
            rewardLabel: 'The conjunction becomes a dangerous new memory',
          },
        },
      ],
    },
  ],
  branchEncounters: [
    {
      id: 'drowned-belfry-cantors',
      choiceId: 'drowned-vow',
      optionId: 'still-the-bells',
      name: 'Cantors of the Pale Belfry',
      sectionIds: ['drowned-pale-belfry'],
      activation: { kind: 'circle', center: [-16, 17], radius: 3.4 },
      objective: 'Silence the drowned cantors before the bell remembers your name',
      spawns: [
        { id: 'drowned-belfry-cantor', kind: 'drownedCantor', implementation: 'existing', role: 'support', sectionId: 'drowned-pale-belfry', position: [-16, 16.5], facingRadians: 0, leashSectionIds: ['drowned-pale-belfry'], anchorId: 'drowned-bell-heart' },
        { id: 'drowned-belfry-wisp-left', kind: 'wisp', implementation: 'existing', role: 'artillery', sectionId: 'drowned-pale-belfry', position: [-18, 18], facingRadians: 0, leashSectionIds: ['drowned-pale-belfry'], anchorId: 'drowned-bell-left', wakeDelaySeconds: 0.45 },
        { id: 'drowned-belfry-wisp-right', kind: 'wisp', implementation: 'existing', role: 'artillery', sectionId: 'drowned-pale-belfry', position: [-14, 18], facingRadians: 0, leashSectionIds: ['drowned-pale-belfry'], anchorId: 'drowned-bell-right', wakeDelaySeconds: 0.8 },
      ],
    },
    {
      id: 'graveglass-dead',
      choiceId: 'drowned-vow',
      optionId: 'take-the-graveglass',
      name: 'The Graveglass Dead',
      sectionIds: ['graveglass-crypt'],
      activation: { kind: 'circle', center: [13, 15], radius: 3.4 },
      objective: 'Take the graveglass from those still reflected inside it',
      spawns: [
        { id: 'graveglass-cantor', kind: 'drownedCantor', implementation: 'existing', role: 'artillery', sectionId: 'graveglass-crypt', position: [13, 17.2], facingRadians: Math.PI, leashSectionIds: ['graveglass-crypt'], anchorId: 'graveglass-center' },
        { id: 'graveglass-initiate-left', kind: 'ashenInitiate', implementation: 'existing', role: 'skirmisher', sectionId: 'graveglass-crypt', position: [11.5, 15], facingRadians: Math.PI, leashSectionIds: ['graveglass-crypt'], anchorId: 'graveglass-left' },
        { id: 'graveglass-initiate-right', kind: 'ashenInitiate', implementation: 'existing', role: 'skirmisher', sectionId: 'graveglass-crypt', position: [14.5, 15], facingRadians: Math.PI, leashSectionIds: ['graveglass-crypt'], anchorId: 'graveglass-right', wakeDelaySeconds: 0.35 },
      ],
    },
    {
      id: 'garden-grafts',
      choiceId: 'verdant-covenant',
      optionId: 'tend-the-seed',
      name: 'Grafts of the Cathedral Glasshouse',
      sectionIds: ['verdant-glasshouse'],
      activation: { kind: 'circle', center: [-3, -35], radius: 3.7 },
      objective: 'Prune the thorn reliquaries without extinguishing the aurora seed',
      spawns: [
        { id: 'glasshouse-reliquary', kind: 'thornReliquary', implementation: 'existing', role: 'support', sectionId: 'verdant-glasshouse', position: [-3, -35], facingRadians: 0, leashSectionIds: ['verdant-glasshouse'], anchorId: 'glasshouse-heart' },
        { id: 'glasshouse-wisp-left', kind: 'wisp', implementation: 'existing', role: 'skirmisher', sectionId: 'verdant-glasshouse', position: [-5, -34], facingRadians: 0, leashSectionIds: ['verdant-glasshouse'], anchorId: 'glasshouse-west', wakeDelaySeconds: 0.35 },
        { id: 'glasshouse-wisp-right', kind: 'wisp', implementation: 'existing', role: 'skirmisher', sectionId: 'verdant-glasshouse', position: [-1, -36], facingRadians: 0, leashSectionIds: ['verdant-glasshouse'], anchorId: 'glasshouse-east', wakeDelaySeconds: 0.7 },
      ],
    },
    {
      id: 'bloodroot-reliquary',
      choiceId: 'verdant-covenant',
      optionId: 'harvest-the-root',
      name: 'Reliquary of the Bloodroot',
      sectionIds: ['bloodroot-basin'],
      activation: { kind: 'circle', center: [17, -35], radius: 3.8 },
      objective: 'Break the rootbound reliquary and claim its living bronze',
      spawns: [
        { id: 'bloodroot-reliquary-heart', kind: 'thornReliquary', implementation: 'existing', role: 'guard', sectionId: 'bloodroot-basin', position: [17, -35], facingRadians: Math.PI, leashSectionIds: ['bloodroot-basin'], anchorId: 'bloodroot-heart' },
        { id: 'bloodroot-initiate-west', kind: 'ashenInitiate', implementation: 'existing', role: 'skirmisher', sectionId: 'bloodroot-basin', position: [14.5, -34], facingRadians: Math.PI, leashSectionIds: ['bloodroot-basin'], anchorId: 'bloodroot-west' },
        { id: 'bloodroot-initiate-east', kind: 'ashenInitiate', implementation: 'existing', role: 'skirmisher', sectionId: 'bloodroot-basin', position: [19, -37], facingRadians: Math.PI, leashSectionIds: ['bloodroot-basin'], anchorId: 'bloodroot-east', wakeDelaySeconds: 0.55 },
      ],
    },
    {
      id: 'ember-choir-penitents',
      choiceId: 'ember-rite',
      optionId: 'still-the-solar-bells',
      name: 'Penitents of the Bell Loft',
      sectionIds: ['ember-cathedral-nave'],
      activation: { kind: 'circle', center: [-7, -49.5], radius: 4 },
      objective: 'Still the vermilion bells and their censer-bearing penitents',
      spawns: [
        { id: 'ember-nave-penitent', kind: 'emberPenitent', implementation: 'existing', role: 'charger', sectionId: 'ember-cathedral-nave', position: [-7, -50.5], facingRadians: 0, leashSectionIds: ['ember-cathedral-nave'], anchorId: 'ember-nave-heart' },
        { id: 'ember-nave-initiate-left', kind: 'ashenInitiate', implementation: 'existing', role: 'skirmisher', sectionId: 'ember-cathedral-nave', position: [-9.4, -48.3], facingRadians: 0, leashSectionIds: ['ember-cathedral-nave'], anchorId: 'ember-nave-left', wakeDelaySeconds: 0.45 },
        { id: 'ember-nave-initiate-right', kind: 'ashenInitiate', implementation: 'existing', role: 'skirmisher', sectionId: 'ember-cathedral-nave', position: [-4.6, -48.3], facingRadians: 0, leashSectionIds: ['ember-cathedral-nave'], anchorId: 'ember-nave-right', wakeDelaySeconds: 0.8 },
      ],
    },
    {
      id: 'ember-furnace-penitents',
      choiceId: 'ember-rite',
      optionId: 'relight-the-sun-heart',
      name: 'Penitents of the Sun-Heart',
      sectionIds: ['ember-sunheart-crypt'],
      activation: { kind: 'circle', center: [19, -50], radius: 4 },
      objective: 'Relight the sun-heart through the furnace penitents',
      spawns: [
        { id: 'ember-furnace-penitent', kind: 'emberPenitent', implementation: 'existing', role: 'charger', sectionId: 'ember-sunheart-crypt', position: [19, -50], facingRadians: Math.PI, leashSectionIds: ['ember-sunheart-crypt'], anchorId: 'ember-furnace-heart' },
        { id: 'ember-furnace-initiate-left', kind: 'ashenInitiate', implementation: 'existing', role: 'skirmisher', sectionId: 'ember-sunheart-crypt', position: [17, -48], facingRadians: Math.PI, leashSectionIds: ['ember-sunheart-crypt'], anchorId: 'ember-furnace-left', wakeDelaySeconds: 0.35 },
        { id: 'ember-furnace-lancer-right', kind: 'astralLancer', implementation: 'existing', role: 'charger', sectionId: 'ember-sunheart-crypt', position: [21, -52], facingRadians: Math.PI, leashSectionIds: ['ember-sunheart-crypt'], anchorId: 'ember-furnace-right', wakeDelaySeconds: 0.75 },
      ],
    },
    {
      id: 'amethyst-null-scribes',
      choiceId: 'amethyst-confession',
      optionId: 'seal-the-null',
      name: 'Scribes of the Null Choir',
      sectionIds: ['amethyst-null-choir'],
      activation: { kind: 'circle', center: [-12, -61], radius: 4.1 },
      objective: 'Seal the null choir before its scribes index your death',
      spawns: [
        { id: 'null-choir-scribe', kind: 'prismScribe', implementation: 'existing', role: 'artillery', sectionId: 'amethyst-null-choir', position: [-12, -61], facingRadians: 0, leashSectionIds: ['amethyst-null-choir'], anchorId: 'null-choir-heart' },
        { id: 'null-choir-wisp-left', kind: 'wisp', implementation: 'existing', role: 'artillery', sectionId: 'amethyst-null-choir', position: [-14, -60], facingRadians: 0, leashSectionIds: ['amethyst-null-choir'], anchorId: 'null-choir-left', wakeDelaySeconds: 0.45 },
        { id: 'null-choir-wisp-right', kind: 'wisp', implementation: 'existing', role: 'artillery', sectionId: 'amethyst-null-choir', position: [-10, -63], facingRadians: 0, leashSectionIds: ['amethyst-null-choir'], anchorId: 'null-choir-right', wakeDelaySeconds: 0.9 },
      ],
    },
    {
      id: 'amethyst-archive-scribes',
      choiceId: 'amethyst-confession',
      optionId: 'drink-the-conjunction',
      name: 'Scribes of the Levitating Index',
      sectionIds: ['levitating-amethyst-archive'],
      activation: { kind: 'circle', center: [16, -61], radius: 4.1 },
      objective: 'Defeat the prism scribes and drink the forbidden conjunction',
      spawns: [
        { id: 'archive-prism-scribe', kind: 'prismScribe', implementation: 'existing', role: 'support', sectionId: 'levitating-amethyst-archive', position: [16, -61], facingRadians: Math.PI, leashSectionIds: ['levitating-amethyst-archive'], anchorId: 'archive-heart' },
        { id: 'archive-seer-left', kind: 'seer', implementation: 'existing', role: 'artillery', sectionId: 'levitating-amethyst-archive', position: [14, -59], facingRadians: Math.PI, leashSectionIds: ['levitating-amethyst-archive'], anchorId: 'archive-left', wakeDelaySeconds: 0.4 },
        { id: 'archive-seer-right', kind: 'seer', implementation: 'existing', role: 'artillery', sectionId: 'levitating-amethyst-archive', position: [18, -63], facingRadians: Math.PI, leashSectionIds: ['levitating-amethyst-archive'], anchorId: 'archive-right', wakeDelaySeconds: 0.8 },
      ],
    },
  ],
  encounters: [
    {
      id: 'ashen-processional-ward',
      name: 'Wardens of the Processional',
      order: 0,
      sectionIds: ['ashen-processional'],
      activation: { kind: 'obb', center: [0, 35], halfExtents: [3.8, 1.5], rotation: 0 },
      rearGateId: 'threshold-portcullis',
      exitGateId: 'moon-seal',
      boss: 'none',
      objective: 'Break the wardens barring the Pale Moon court',
      spawns: [
        {
          id: 'processional-wisp-left',
          kind: 'wisp',
          implementation: 'existing',
          role: 'artillery',
          sectionId: 'ashen-processional',
          position: [-2.5, 35],
          facingRadians: 0,
          leashSectionIds: ['ashen-processional'],
          anchorId: 'processional-left-vantage',
        },
        {
          id: 'processional-sentinel',
          kind: 'sentinel',
          implementation: 'existing',
          role: 'guard',
          sectionId: 'ashen-processional',
          position: [0, 31],
          facingRadians: 0,
          leashSectionIds: ['ashen-processional'],
          anchorId: 'processional-center-guard',
          wakeDelaySeconds: 0.3,
        },
        {
          id: 'processional-wisp-right',
          kind: 'wisp',
          implementation: 'existing',
          role: 'artillery',
          sectionId: 'ashen-processional',
          position: [2.3, 28.5],
          facingRadians: 0,
          leashSectionIds: ['ashen-processional'],
          anchorId: 'processional-right-vantage',
          wakeDelaySeconds: 0.65,
        },
      ],
    },
    {
      id: 'fallen-orbit-crossing',
      name: 'The Fallen-Orbit Crossing',
      order: 1,
      sectionIds: ['fallen-orbit-bridge'],
      activation: { kind: 'circle', center: [-4, 13.8], radius: 1.8 },
      rearGateId: 'moon-seal',
      exitGateId: 'orrery-seal',
      boss: 'none',
      objective: 'Cross the bridge and silence its astral lance',
      spawns: [
        {
          id: 'fallen-orbit-sentinel',
          kind: 'sentinel',
          implementation: 'existing',
          role: 'guard',
          sectionId: 'fallen-orbit-bridge',
          position: [-5.9, 14],
          facingRadians: Math.PI / 6,
          leashSectionIds: ['fallen-orbit-bridge'],
        },
        {
          id: 'fallen-orbit-lancer',
          kind: 'astralLancer',
          implementation: 'planned',
          role: 'charger',
          sectionId: 'fallen-orbit-bridge',
          position: [-6, 10],
          facingRadians: Math.PI / 6,
          leashSectionIds: ['fallen-orbit-bridge'],
          anchorId: 'fallen-orbit-midspan',
          wakeDelaySeconds: 0.45,
        },
        {
          id: 'fallen-orbit-wisp',
          kind: 'wisp',
          implementation: 'existing',
          role: 'artillery',
          sectionId: 'fallen-orbit-bridge',
          position: [-10, 3.5],
          facingRadians: Math.PI / 6,
          leashSectionIds: ['fallen-orbit-bridge'],
          anchorId: 'fallen-orbit-far-vantage',
        },
      ],
    },
    {
      id: 'orrery-castellan',
      name: 'Orrery Castellan',
      order: 2,
      sectionIds: ['orrery-court'],
      activation: { kind: 'circle', center: [-11.5, -3.5], radius: 4 },
      rearGateId: 'orrery-seal',
      exitGateId: 'aurora-seal',
      boss: 'midpoint',
      objective: 'Defeat the Orrery Castellan',
      spawns: [
        {
          id: 'orrery-castellan-boss',
          kind: 'orreryCastellan',
          implementation: 'planned',
          role: 'boss',
          sectionId: 'orrery-court',
          position: [-11.5, -4],
          facingRadians: 0,
          leashSectionIds: ['orrery-court'],
          anchorId: 'orrery-heart',
        },
      ],
    },
    {
      id: 'choristers-of-the-sundered-span',
      name: 'Choristers of the Sundered Span',
      order: 3,
      sectionIds: ['sundered-causeway', 'conjunction-cloister'],
      activation: { kind: 'obb', center: [7, -37], halfExtents: [1.8, 1.1], rotation: 0 },
      rearGateId: 'aurora-seal',
      exitGateId: 'eclipse-seal',
      boss: 'none',
      objective: 'Break the eclipse choir and restore the Lost Conjunction',
      spawns: [
        {
          id: 'sundered-ashen-initiate',
          kind: 'ashenInitiate',
          implementation: 'planned',
          role: 'skirmisher',
          sectionId: 'sundered-causeway',
          position: [7, -31],
          facingRadians: 0,
          leashSectionIds: ['sundered-causeway'],
          anchorId: 'sundered-entry',
        },
        {
          id: 'sundered-astral-lancer',
          kind: 'astralLancer',
          implementation: 'planned',
          role: 'charger',
          sectionId: 'sundered-causeway',
          position: [7, -37],
          facingRadians: 0,
          leashSectionIds: ['sundered-causeway'],
          anchorId: 'sundered-charge-lane',
          wakeDelaySeconds: 0.35,
        },
        {
          id: 'cloister-seer',
          kind: 'seer',
          implementation: 'existing',
          role: 'artillery',
          sectionId: 'conjunction-cloister',
          position: [3.1, -42.8],
          facingRadians: 0,
          leashSectionIds: ['conjunction-cloister'],
          anchorId: 'cloister-seer-focus',
          wakeDelaySeconds: 0.8,
        },
        {
          id: 'cloister-chorister',
          kind: 'eclipseChorister',
          implementation: 'planned',
          role: 'support',
          sectionId: 'conjunction-cloister',
          position: [10, -44],
          facingRadians: 0,
          leashSectionIds: ['conjunction-cloister'],
          anchorId: 'cloister-choir-dais',
          wakeDelaySeconds: 1.1,
        },
      ],
    },
    {
      id: 'eclipse-archon',
      name: 'Eclipse Archon',
      order: 4,
      sectionIds: ['moonfall-observatory'],
      activation: { kind: 'circle', center: [0, -67], radius: 6 },
      rearGateId: 'eclipse-seal',
      boss: 'final',
      objective: 'Defeat the Eclipse Archon and restore the firmament',
      spawns: [
        {
          id: 'eclipse-archon-boss',
          kind: 'eclipseArchon',
          implementation: 'existing',
          role: 'boss',
          sectionId: 'moonfall-observatory',
          position: [0, -68],
          facingRadians: 0,
          leashSectionIds: ['moonfall-observatory'],
          anchorId: 'observatory-eclipse-seal',
        },
      ],
    },
  ],
} as const satisfies CampaignRouteDefinition);

export const FIRMAMENT_ROUTE_WALKABLE: readonly RouteShape[] = FIRMAMENT_ROUTE.sections.flatMap<RouteShape>(
  (section) => section.walkable,
);

export const FIRMAMENT_ROUTE_ALL_SECTIONS = [
  ...FIRMAMENT_ROUTE.sections,
  ...(FIRMAMENT_ROUTE.branchSections ?? []),
] as const;

export const FIRMAMENT_ROUTE_ALL_WALKABLE: readonly RouteShape[] = FIRMAMENT_ROUTE_ALL_SECTIONS.flatMap<RouteShape>(
  (section) => section.walkable,
);

export const FIRMAMENT_ROUTE_ALL_ENCOUNTERS = [
  ...FIRMAMENT_ROUTE.encounters,
  ...(FIRMAMENT_ROUTE.branchEncounters ?? []),
] as const;
