import type { CampaignRouteDefinition, RouteShape } from './RouteTypes';
import { assertValidRouteDefinition } from './validateRoute';

/**
 * The first authored pilgrimage through the Last Firmament. Coordinates are
 * renderer-independent X/Z tuples so simulation, validation, and tooling can
 * consume this definition without constructing Three.js objects.
 */
export const FIRMAMENT_ROUTE = assertValidRouteDefinition({
  version: 1,
  id: 'last-firmament-pilgrimage',
  name: 'The Pilgrimage to Moonfall Observatory',
  start: {
    sectionId: 'spiral-threshold',
    position: [0, 46],
    facingRadians: Math.PI,
  },
  requirements: {
    encounterCount: 5,
    minimumBridgeSections: 3,
    relicOrder: ['moon', 'aurora', 'constellation'],
    enemyKinds: [
      'wisp',
      'sentinel',
      'seer',
      'ashenInitiate',
      'astralLancer',
      'eclipseChorister',
      'orreryCastellan',
      'eclipseArchon',
    ],
  },
  sections: [
    {
      id: 'spiral-threshold',
      name: 'Spiral Threshold',
      order: 0,
      kind: 'safe',
      safe: true,
      connectsTo: ['ashen-processional'],
      walkable: [{ kind: 'circle', center: [0, 46], radius: 7 }],
      cameraForward: [0, -1],
      enemyAnchors: [],
    },
    {
      id: 'ashen-processional',
      name: 'Ashen Processional',
      order: 1,
      kind: 'processional',
      safe: false,
      connectsTo: ['spiral-threshold', 'moon-court'],
      walkable: [{ kind: 'obb', center: [0, 34], halfExtents: [4.6, 8.2], rotation: 0 }],
      cameraForward: [0, -1],
      enemyAnchors: [
        { id: 'processional-left-vantage', position: [-2.5, 35] },
        { id: 'processional-center-guard', position: [0, 31] },
        { id: 'processional-right-vantage', position: [2.3, 28.5] },
      ],
    },
    {
      id: 'moon-court',
      name: 'Court of the Pale Moon',
      order: 2,
      kind: 'court',
      safe: true,
      connectsTo: ['ashen-processional', 'fallen-orbit-bridge'],
      walkable: [{ kind: 'circle', center: [0, 22], radius: 6.5 }],
      cameraForward: [-0.5, -0.866],
      enemyAnchors: [],
    },
    {
      id: 'fallen-orbit-bridge',
      name: 'Bridge of Fallen Orbits',
      order: 3,
      kind: 'bridge',
      safe: false,
      connectsTo: ['moon-court', 'orrery-court'],
      walkable: [{ kind: 'obb', center: [-5.5, 11.5], halfExtents: [2.4, 11.5], rotation: -Math.PI / 6 }],
      cameraForward: [-0.5, -0.866],
      enemyAnchors: [
        { id: 'fallen-orbit-entry', position: [-1, 19] },
        { id: 'fallen-orbit-midspan', position: [-6, 10] },
        { id: 'fallen-orbit-far-vantage', position: [-10, 3.5] },
      ],
    },
    {
      id: 'orrery-court',
      name: 'Court of the Broken Orrery',
      order: 4,
      kind: 'boss-arena',
      safe: false,
      connectsTo: ['fallen-orbit-bridge', 'aurora-span'],
      walkable: [{ kind: 'circle', center: [-11.5, -3.5], radius: 7.2 }],
      cameraForward: [0.707, -0.707],
      enemyAnchors: [{ id: 'orrery-heart', position: [-11.5, -4] }],
    },
    {
      id: 'aurora-span',
      name: 'Aurora Span',
      order: 5,
      kind: 'bridge',
      safe: true,
      connectsTo: ['orrery-court', 'aurora-refuge'],
      walkable: [{ kind: 'obb', center: [-2.5, -14.5], halfExtents: [2.5, 13.5], rotation: Math.PI / 4 }],
      cameraForward: [0.707, -0.707],
      enemyAnchors: [],
    },
    {
      id: 'aurora-refuge',
      name: 'Aurora Refuge',
      order: 6,
      kind: 'refuge',
      safe: true,
      connectsTo: ['aurora-span', 'sundered-causeway'],
      walkable: [{ kind: 'circle', center: [7, -25], radius: 5.8 }],
      cameraForward: [0, -1],
      enemyAnchors: [],
    },
    {
      id: 'sundered-causeway',
      name: 'Sundered Causeway',
      order: 7,
      kind: 'causeway',
      safe: false,
      connectsTo: ['aurora-refuge', 'conjunction-cloister'],
      walkable: [{ kind: 'obb', center: [7, -35], halfExtents: [2.3, 7.5], rotation: 0 }],
      cameraForward: [0, -1],
      enemyAnchors: [
        { id: 'sundered-entry', position: [7, -31] },
        { id: 'sundered-charge-lane', position: [7, -37] },
      ],
    },
    {
      id: 'conjunction-cloister',
      name: 'Conjunction Cloister',
      order: 8,
      kind: 'court',
      safe: false,
      connectsTo: ['sundered-causeway', 'eclipse-causeway'],
      walkable: [{ kind: 'circle', center: [7, -46], radius: 7 }],
      cameraForward: [-0.259, -0.966],
      enemyAnchors: [
        { id: 'cloister-seer-focus', position: [4, -44] },
        { id: 'cloister-choir-dais', position: [7, -47] },
      ],
    },
    {
      id: 'eclipse-causeway',
      name: 'Eclipse Causeway',
      order: 9,
      kind: 'causeway',
      safe: true,
      connectsTo: ['conjunction-cloister', 'moonfall-observatory'],
      walkable: [{ kind: 'obb', center: [3.5, -56], halfExtents: [2.7, 8.4], rotation: -Math.PI / 12 }],
      cameraForward: [-0.259, -0.966],
      enemyAnchors: [],
    },
    {
      id: 'moonfall-observatory',
      name: 'Moonfall Observatory',
      order: 10,
      kind: 'boss-arena',
      safe: false,
      connectsTo: ['eclipse-causeway'],
      walkable: [{ kind: 'circle', center: [0, -67], radius: 10 }],
      cameraForward: [0, -1],
      enemyAnchors: [{ id: 'observatory-eclipse-seal', position: [0, -68] }],
    },
  ],
  gates: [
    {
      id: 'threshold-portcullis',
      name: 'Threshold Portcullis',
      sectionId: 'ashen-processional',
      collider: { a: [-5, 40.5], b: [5, 40.5], thickness: 0.42 },
      initialState: 'open',
    },
    {
      id: 'moon-seal',
      name: 'Pale Moon Seal',
      sectionId: 'moon-court',
      collider: { a: [-5.2, 26.4], b: [5.2, 26.4], thickness: 0.48 },
      initialState: 'closed',
    },
    {
      id: 'orrery-seal',
      name: 'Broken Orrery Seal',
      sectionId: 'fallen-orbit-bridge',
      collider: { a: [-13.7427, 4.4226], b: [-7.5073, 0.8226], thickness: 0.5 },
      initialState: 'closed',
    },
    {
      id: 'aurora-seal',
      name: 'Verdant Aurora Seal',
      sectionId: 'aurora-span',
      collider: { a: [-8.9042, -12.9042], b: [-4.0958, -8.0958], thickness: 0.5 },
      initialState: 'closed',
    },
    {
      id: 'eclipse-seal',
      name: 'Conjunction Eclipse Seal',
      sectionId: 'eclipse-causeway',
      collider: { a: [1.0227, -52.5683], b: [7.9773, -54.4317], thickness: 0.56 },
      initialState: 'closed',
    },
  ],
  checkpoints: [
    {
      id: 'moon-relic',
      name: 'Body of the Pale Moon',
      order: 0,
      sectionId: 'moon-court',
      position: [0, 22],
      facingRadians: -Math.PI / 6,
      activationRadius: 1.8,
      relicKind: 'moon',
      unlocksAfterEncounterId: 'ashen-processional-ward',
    },
    {
      id: 'aurora-relic',
      name: 'Body of the Verdant Aurora',
      order: 1,
      sectionId: 'aurora-refuge',
      position: [7, -25],
      facingRadians: Math.PI,
      activationRadius: 1.8,
      relicKind: 'aurora',
      unlocksAfterEncounterId: 'orrery-castellan',
    },
    {
      id: 'constellation-relic',
      name: 'Body of the Lost Conjunction',
      order: 2,
      sectionId: 'conjunction-cloister',
      position: [7, -46],
      facingRadians: -Math.PI / 12,
      activationRadius: 1.8,
      relicKind: 'constellation',
      unlocksAfterEncounterId: 'choristers-of-the-sundered-span',
    },
  ],
  encounters: [
    {
      id: 'ashen-processional-ward',
      name: 'Wardens of the Processional',
      order: 0,
      sectionIds: ['ashen-processional'],
      activation: { kind: 'obb', center: [0, 35], halfExtents: [3.8, 1.5], rotation: 0 },
      rearGateId: 'threshold-portcullis',
      exitGateId: 'moon-seal',
      boss: 'none',
      objective: 'Break the wardens barring the Pale Moon court',
      spawns: [
        {
          id: 'processional-wisp-left',
          kind: 'wisp',
          implementation: 'existing',
          role: 'artillery',
          sectionId: 'ashen-processional',
          position: [-2.5, 35],
          facingRadians: 0,
          leashSectionIds: ['ashen-processional'],
          anchorId: 'processional-left-vantage',
        },
        {
          id: 'processional-sentinel',
          kind: 'sentinel',
          implementation: 'existing',
          role: 'guard',
          sectionId: 'ashen-processional',
          position: [0, 31],
          facingRadians: 0,
          leashSectionIds: ['ashen-processional'],
          anchorId: 'processional-center-guard',
          wakeDelaySeconds: 0.3,
        },
        {
          id: 'processional-wisp-right',
          kind: 'wisp',
          implementation: 'existing',
          role: 'artillery',
          sectionId: 'ashen-processional',
          position: [2.3, 28.5],
          facingRadians: 0,
          leashSectionIds: ['ashen-processional'],
          anchorId: 'processional-right-vantage',
          wakeDelaySeconds: 0.65,
        },
      ],
    },
    {
      id: 'fallen-orbit-crossing',
      name: 'The Fallen-Orbit Crossing',
      order: 1,
      sectionIds: ['fallen-orbit-bridge'],
      activation: { kind: 'circle', center: [-1, 19], radius: 1.8 },
      rearGateId: 'moon-seal',
      exitGateId: 'orrery-seal',
      boss: 'none',
      objective: 'Cross the bridge and silence its astral lance',
      spawns: [
        {
          id: 'fallen-orbit-sentinel',
          kind: 'sentinel',
          implementation: 'existing',
          role: 'guard',
          sectionId: 'fallen-orbit-bridge',
          position: [-3, 15.2],
          facingRadians: Math.PI / 6,
          leashSectionIds: ['fallen-orbit-bridge'],
        },
        {
          id: 'fallen-orbit-lancer',
          kind: 'astralLancer',
          implementation: 'planned',
          role: 'charger',
          sectionId: 'fallen-orbit-bridge',
          position: [-6, 10],
          facingRadians: Math.PI / 6,
          leashSectionIds: ['fallen-orbit-bridge'],
          anchorId: 'fallen-orbit-midspan',
          wakeDelaySeconds: 0.45,
        },
        {
          id: 'fallen-orbit-wisp',
          kind: 'wisp',
          implementation: 'existing',
          role: 'artillery',
          sectionId: 'fallen-orbit-bridge',
          position: [-10, 3.5],
          facingRadians: Math.PI / 6,
          leashSectionIds: ['fallen-orbit-bridge'],
          anchorId: 'fallen-orbit-far-vantage',
        },
      ],
    },
    {
      id: 'orrery-castellan',
      name: 'Orrery Castellan',
      order: 2,
      sectionIds: ['orrery-court'],
      activation: { kind: 'circle', center: [-11.5, -3.5], radius: 4 },
      rearGateId: 'orrery-seal',
      exitGateId: 'aurora-seal',
      boss: 'midpoint',
      objective: 'Defeat the Orrery Castellan',
      spawns: [
        {
          id: 'orrery-castellan-boss',
          kind: 'orreryCastellan',
          implementation: 'planned',
          role: 'boss',
          sectionId: 'orrery-court',
          position: [-11.5, -4],
          facingRadians: 0,
          leashSectionIds: ['orrery-court'],
          anchorId: 'orrery-heart',
        },
      ],
    },
    {
      id: 'choristers-of-the-sundered-span',
      name: 'Choristers of the Sundered Span',
      order: 3,
      sectionIds: ['sundered-causeway', 'conjunction-cloister'],
      activation: { kind: 'obb', center: [7, -32], halfExtents: [1.8, 1.1], rotation: 0 },
      rearGateId: 'aurora-seal',
      exitGateId: 'eclipse-seal',
      boss: 'none',
      objective: 'Break the eclipse choir and restore the Lost Conjunction',
      spawns: [
        {
          id: 'sundered-ashen-initiate',
          kind: 'ashenInitiate',
          implementation: 'planned',
          role: 'skirmisher',
          sectionId: 'sundered-causeway',
          position: [7, -31],
          facingRadians: 0,
          leashSectionIds: ['sundered-causeway'],
          anchorId: 'sundered-entry',
        },
        {
          id: 'sundered-astral-lancer',
          kind: 'astralLancer',
          implementation: 'planned',
          role: 'charger',
          sectionId: 'sundered-causeway',
          position: [7, -37],
          facingRadians: 0,
          leashSectionIds: ['sundered-causeway'],
          anchorId: 'sundered-charge-lane',
          wakeDelaySeconds: 0.35,
        },
        {
          id: 'cloister-seer',
          kind: 'seer',
          implementation: 'existing',
          role: 'artillery',
          sectionId: 'conjunction-cloister',
          position: [4, -44],
          facingRadians: 0,
          leashSectionIds: ['conjunction-cloister'],
          anchorId: 'cloister-seer-focus',
          wakeDelaySeconds: 0.8,
        },
        {
          id: 'cloister-chorister',
          kind: 'eclipseChorister',
          implementation: 'planned',
          role: 'support',
          sectionId: 'conjunction-cloister',
          position: [7, -47],
          facingRadians: 0,
          leashSectionIds: ['conjunction-cloister'],
          anchorId: 'cloister-choir-dais',
          wakeDelaySeconds: 1.1,
        },
      ],
    },
    {
      id: 'eclipse-archon',
      name: 'Eclipse Archon',
      order: 4,
      sectionIds: ['moonfall-observatory'],
      activation: { kind: 'circle', center: [0, -67], radius: 6 },
      rearGateId: 'eclipse-seal',
      boss: 'final',
      objective: 'Defeat the Eclipse Archon and restore the firmament',
      spawns: [
        {
          id: 'eclipse-archon-boss',
          kind: 'eclipseArchon',
          implementation: 'existing',
          role: 'boss',
          sectionId: 'moonfall-observatory',
          position: [0, -68],
          facingRadians: 0,
          leashSectionIds: ['moonfall-observatory'],
          anchorId: 'observatory-eclipse-seal',
        },
      ],
    },
  ],
} as const satisfies CampaignRouteDefinition);

export const FIRMAMENT_ROUTE_WALKABLE: readonly RouteShape[] = FIRMAMENT_ROUTE.sections.flatMap<RouteShape>(
  (section) => section.walkable,
);
